# Generated by Django 5.1.4 on 2026-05-27 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Clínica',
                'verbose_name_plural': 'Clínicas',
            },
        ),
        migrations.CreateModel(
            name='ClinicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clinic_logos/')),
                ('primary_color', models.CharField(default='#2563EB', max_length=7)),
                ('secondary_color', models.CharField(default='#1E40AF', max_length=7)),
                ('portal_title', models.CharField(default='Portal de Laudos', max_length=100)),
                ('portal_subtitle', models.CharField(blank=True, max_length=200)),
                ('welcome_message', models.TextField(blank=True)),
                ('footer_text', models.CharField(blank=True, max_length=200)),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='clinics.clinic')),
            ],
            options={
                'verbose_name': 'Configurações da Clínica',
            },
        ),
    ]
