# Generated by Django 5.1.4 on 2026-05-27 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='license_active',
            field=models.BooleanField(default=True, verbose_name='Licença ativa'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='license_notes',
            field=models.TextField(blank=True, verbose_name='Observações da licença'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='license_valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Válida até'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='plan',
            field=models.CharField(choices=[('free', 'Gratuito'), ('basic', 'Básico'), ('pro', 'Profissional')], default='free', max_length=20),
        ),
    ]
