# Generated by Django 5.1.4 on 2026-05-27 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Administrador'), ('secretary', 'Secretária'), ('doctor', 'Médica'), ('patient', 'Paciente')], default='secretary', max_length=20),
        ),
    ]
