# Generated by Django 5.1.4 on 2026-05-27 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='doctor_notes',
            field=models.TextField(blank=True, verbose_name='Observações do médico'),
        ),
        migrations.AddField(
            model_name='report',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Enviado'), ('approved', 'Aprovado'), ('signed', 'Assinado'), ('published', 'Publicado'), ('rejected', 'Rejeitado'), ('revision', 'Em Revisão')], default='uploaded', max_length=20),
        ),
    ]
